spring.application.name=GharSe
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#FOR DEVELOPMENT ONLY
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true